# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "10.10.10.10"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../../Libs/vagrant-chef/chef/cookbooks"
    chef.data_bags_path = "../../../Libs/vagrant-chef/chef/data_bags"
    chef.add_recipe "apt"
    chef.add_recipe "git"
    chef.add_recipe "dotdeb"
    chef.add_recipe "dotdeb::php54"
    chef.add_recipe "apache2"
    chef.add_recipe "apache2::mod_rewrite"
    chef.add_recipe "apache2::mod_ssl"
    chef.add_recipe "mysql::server"
    chef.add_recipe "php"
    chef.add_recipe "php::module_mysql"
    chef.add_recipe "chef-php-extra"
    chef.add_recipe "apache2::mod_php5"
    chef.add_recipe "database::mysql"
    chef.add_recipe "apache-sites"
    chef.add_recipe "mysql-databases"
    chef.add_recipe "composer"
    chef.add_recipe "phpunit"

    chef.json.merge!({
      "mysql" => {
          "server_root_password" => "password",
          "server_debian_password" => "password",
          "server_repl_password" => "password",
          "bind_address" => "10.10.10.10"
        },
        "databases" => {
            "create" => ["merc"]
        },
        "sites" => ["default"]
    })
  end
end